name: Send In Progress Notification

on:
  workflow_call:

jobs:
  notify_in_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Set Workflow Link
        id: workflow_link
        run: echo "##[set-output name=link]https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Set Branch Name
        id: branch_name
        run: |
          ref=${{ github.ref }}
          branch_name=${ref#refs/heads/}
          echo "##[set-output name=name;]$branch_name"

      - name: Send notification - In Progress
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEPLOY_IN_PROGRESS }}
          APP_NAME: ${{ github.repository }}
          BRANCH_NAME: ${{ steps.branch_name.outputs.name }}
          WORKFLOW_LINK: ${{ steps.workflow_link.outputs.link }}
        run: |
          payload=$(jq -n \
            --arg app_name "$APP_NAME" \
            --arg branch "$BRANCH_NAME" \
            --arg workflow_link "$WORKFLOW_LINK" \
            '{
              "app_name": $app_name,
              "branch": $branch,
              "workflow_link": $workflow_link
            }')
          curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK_URL