name: Send Result Notification

on:
  workflow_call:

jobs:
  notify_in_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Set Workflow Link
        id: workflow_link
        run: echo "##[set-output name=link]https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Set Branch Name
        id: branch_name
        run: |
          ref=${{ github.ref }}
          branch_name=${ref#refs/heads/}
          echo "##[set-output name=name;]$branch_name"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Send notification - Completed
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "app_name": ${{ github.repository }},
              "branch": ${{ steps.branch_name.outputs.name }},
              "workflow_link": ${{ steps.workflow_link.outputs.link }}
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEPLOY_COMPLETED }}

      - name: Send notification - Failed
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "app_name": "${{ github.repository }}",
              "branch": "${{ steps.branch_name.outputs.name }}",
              "workflow_link": "${{ steps.workflow_link.outputs.link }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEPLOY_FAILED }}
